model:
  model_name: CompVis/stable-diffusion-v1-4
  huggingface_token: PLACE YOUR TOKEN HERE
  
generation:
  environment_name: fing
  output_dir: /mnt/ml/outputs
  host: localhost
  port: 9147
  log_level: DEBUG
  log_filename: log/generator.log
  model_cache_dir: /tmp
  x_api_key_enabled: false
  x_api_key_list:
