model: 
  model_name: CompVis/stable-diffusion-v1-4
  guidance_scale: 7.5

generation:
  output_dir: /mnt/ml/outputs
  host: localhost
  port: 9147
  log_level: DEBUG
  log_filename: log/generator.log

api:
  host: 0.0.0.0
  port: 3010
  log_level: DEBUG
  log_filename: log/api.log